apiVersion: v1
kind: Pod
metadata:
  name: hello-world-enclave
spec:
  containers:
    - name: nitro-cli
      image: spkane/nitro-cli:latest
      # At the moment this is here, so one can exec into
      # the container and just try "run.sh"
      command: ["/enclave/sleep.sh"]
      imagePullPolicy: Always
      ports:
        # TODO: socat the enclave console to some port
        - name: console
          containerPort: 80
          protocol: TCP
      resources:
        limits:
          smarter-devices/nitro_enclaves: "1"
          hugepages-2Mi: 512Mi
          memory: 2Gi
        requests:
          smarter-devices/nitro_enclaves: "1"
          hugepages-2Mi: 512Mi
      volumeMounts:
      - name: dockersock
        mountPath: "/var/run/docker.sock"
      - mountPath: /dev/hugepages
        name: hugepage
        readOnly: false
  tolerations:
  - effect: NoSchedule
    operator: Exists
  - effect: NoExecute
    operator: Exists
  volumes:
    - name: dockersock
      hostPath:
        path: /var/run/docker.sock
    - name: hugepage
      emptyDir:
        medium: HugePages

